"""atualizando a tabela de despesas

Revision ID: 2e95828b00a6
Revises: d3678687f458
Create Date: 2022-03-18 16:48:00.809144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e95828b00a6'
down_revision = 'd3678687f458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('descricao', sa.String(), nullable=True))
    op.add_column('despesas', sa.Column('data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('despesas', 'data')
    op.drop_column('despesas', 'descricao')
    # ### end Alembic commands ###
