"""Outra tentativa

Revision ID: 601b7ba79cf1
Revises: f30ac5e96926
Create Date: 2022-03-17 18:07:40.998709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601b7ba79cf1'
down_revision = 'f30ac5e96926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id_despesa', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_despesa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    # ### end Alembic commands ###
